# Generated by Django 2.1.7 on 2019-03-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190325_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='identifier',
            new_name='defect_id',
        ),
    ]
