# Generated by Django 2.1.7 on 2019-03-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0008_article_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='defect_id',
        ),
    ]
