# Generated by Django 2.1.7 on 2019-03-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0009_remove_article_defect_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='classification',
        ),
    ]
