# Generated by Django 2.1.7 on 2019-03-28 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0013_delete_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='classification',
        ),
    ]
