# Generated by Django 2.1.8 on 2019-04-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0014_remove_article_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='classification',
            field=models.CharField(default='Not Classified', max_length=20),
        ),
    ]
