# Generated by Django 2.1.7 on 2019-04-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0015_article_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(choices=[(0, 'csv'), (1, 'Entry')], default='Entry', max_length=20),
        ),
    ]
