# Generated by Django 2.1.7 on 2019-04-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0016_auto_20190402_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(choices=[('csv', 'csv'), ('Entry', 'Entry')], default='Entry', max_length=20),
        ),
    ]
