# Generated by Django 2.1.7 on 2019-04-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0018_auto_20190402_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reclassification',
            field=models.CharField(choices=[('compliance', 'COMPLIANCE'), ('functional', 'FUNCTIONAL'), ('performance', 'PERFORMANCE'), ('reliability and scalability issues', 'RELIABILITY AND SCALABILITY ISSUES'), ('security', 'SECURITY'), ('usability', 'USABILITY')], default='Not Reclassified Yet', max_length=50),
        ),
    ]
